package com.kosta.exception;

public class Basic2 {

	public static void main(String[] args) {

		int res = 0;
		try {
			//코드라인
			System.out.println("1. try/0");
			int num = 100;
			//int res = num/50; 위에다 초기화해줬으니 int빼자. Sysout(res)를 못찍으니까.
			res = num/0;        //num/0이면 문제되는 코드다. catch문으로 간다.
			
		} catch(ArithmeticException e) {
			System.out.println(e.getMessage());
			System.out.println("1");
		} catch(Exception e) {
			System.out.println(e.getMessage());
			System.out.println("2");
		}

		try {
			System.out.println("4. try(배열코드)");
			int[] arr = {1, 2, 3};
			System.out.println(arr[5]);
		}
		
	}
}

